version: '3.4'

services:

  mssql:
    build:
      context: .
      dockerfile: Databases/MSSQL/Dockerfile
    environment:
     - ACCEPT_EULA=Y
     # Developer, Express, Standard, Enterprise, EnterpriseCore
     - MSSQL_PID=Developer
     - SA_PASSWORD=yourStrong(!)Password
    ports:
     - "1433:1433"
    volumes:
     - ./Databases/MSSQL/data:/var/opt/mssql/data
     - ./Databases/MSSQL/log:/var/opt/mssql/log
     - ./Databases/MSSQL/secrets:/var/opt/mssql/secrets
     - ./Databases/MSSQL/backups:/var/opt/mssql/backups

  rabbitmq:
    image: rabbitmq:3.9.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  owspublicapi:
    image: ${REGISTRY:-ows}/owspublicapi:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSPublicAPI/Dockerfile
    ports:
    - "44302:80"
    - "44303:443"
    depends_on:
    - mssql
    - rabbitmq

  owsinstancemanagement:
    image: ${REGISTRY:-ows}/owsinstancemanagement:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: OWSInstanceManagement/Dockerfile
    ports:
    - "44328:80"
    - "44329:443"
    depends_on:
    - mssql
    - rabbitmq
