version: '3.4'

services:
  mssql:
    build:
      context: .
      dockerfile: Databases/MSSQL/Dockerfile
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=yourStrong(!)Password
    ports:
     - "1433:1433"
  owspublicapi:
    image: ${DOCKER_REGISTRY-}owspublicapi
    build:
      context: .
      dockerfile: OWSPublicAPI/Dockerfile
    ports:
    - "44303:443"

  owsinstancemanagement:
    image: ${DOCKER_REGISTRY-}owsinstancemanagement
    build:
      context: .
      dockerfile: OWSInstanceManagement/Dockerfile
    ports:
    - "44329:443"
