version: '3.4'

services:
  owspublicapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /usr/.aspnet/https:/root/.aspnet/https:ro
  owsinstancemanagement:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /usr/.aspnet/https:/root/.aspnet/https:ro
  owscharacterpersistence:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /usr/.aspnet/https:/root/.aspnet/https:ro
  owsstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - /usr/.aspnet/https:/root/.aspnet/https:ro
